[package]
name = "just_one_pass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
rpassword = "7.3.1"
sha3 = "0.10.8"

